
version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  aws-ebcli: circleci/aws-elastic-beanstalk@2.0.1
  
  browser-tools: circleci/browser-tools@1.2.2


jobs:
  deploy:
    docker:
      
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - browser-tools/install-chrome
      - aws-cli/setup:
          profile-name: udagram
      - aws-ebcli/setup
      - run:
          name: Backend-API install
          command: npm run backend:install
      - run:
          name: Frontend install
          command: npm run frontend:install
      - run:
          name: Backend-API testing
          command: npm run backend:test
      - run:
         name: Frontend testing
         command: npm run frontend:test
      - run:
          name: Backend-API build
          command: npm run backend:build
      - run:
          name: Frontend build
          command: npm run frontend:build
      - run:
          name: Backend-API deploy
          command: npm run backend:deploy
      - run:
          name: Frontend deploy
          command: npm run frontend:deploy

# Workflows to combine jobs - here just one :-)
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
